name: 'Run misspell with reviewdog'
description: '🐶 Run misspell with reviewdog on pull requests to improve code review experience.'
author: 'step-security'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  locale:
    description: '-locale flag of misspell. (US/UK)'
    default: ''
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  ignore:
    description: 'Comma-separated words to ignore'
    default: ''
  path:
    description: "Base directory to run misspell. Same as `[path]` of `find` command."
    default: '.'
  pattern:
    description: "File patterns of target files. Same as `-name [pattern]` of `find` command."
    default: '*'
  exclude:
    description: "Exclude patterns of target files. Same as `-not -path [exclude]` of `find` command."
    default: ''
  filter_mode:
    description: "Filtering mode for the reviewdog command [added,diff_context,file,nofilter]."
    default: 'added'
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog.
      Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: "Deprecated, use `fail_level` instead. Exit code for reviewdog when errors are found [true,false]."
    deprecationMessage: Deprecated, use `fail_level` instead.
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/action-misspell@sha256:sha256:5a2c3e73e6217d7376244dead79c3183deed9940d0ee2f3e14e71e77bd7184eb'
branding:
  icon: 'edit'
  color: 'gray-dark'
